### Data processing

#### Importing libraries

In [3]:
%pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.10.9-cp312-cp312-win_amd64.whl.metadata (52 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.62.1-cp312-cp312-win_amd64.whl.metadata (119 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp312-cp312-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.23 in c:\users\riddhi dhara\anaconda3\envs\lec5_env\lib\site-packages (from matplotlib) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\riddhi dhara\anaconda3\envs\lec5_env\lib\site-packages (from matplotlib) (25.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.2.0-cp312-cp312-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\riddhi dhara\anaconda3\envs\lec5_env\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\riddhi dhara\anaconda3\envs\lec5_env\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.9-cp312-cp312-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   ------- -------------------------------- 1.6/8.2 MB 4.9 MB/s eta 0:00:02
   ------------ --------------------------- 2.6/8.2 MB 4.6 MB/s eta 0:00:02
   ---------------- ----------------------- 3.4/8.2 MB 4.4 MB/s eta 0:00:02
   ------------------- -------------------- 3.9/8.2 MB 4.0 MB/s eta 0:00:02
   --------------------- ------------------ 4.5/8.2 MB 3.8 MB/s eta 0:00:01
   ------------------------ --------------- 5.0/8.2 MB 3.4 MB/s eta 0:00:01
   ------------------------ --------------- 5.0/8.2 MB 3.4 MB/s eta 0:00:01
   ------------------------- -------------- 5.2/8.2 MB 3.1 MB/s eta 0:00:01
   -------------------------- ------------- 5.5/8.2 MB 2.9 MB/s eta 0:00:01
   ---------------------------- ----------- 5.8/8.2 MB 2.6 MB/s eta 0:00:01
   ---------------------------- ----------- 5.8/8.2 MB 2.6 MB/s eta 0:00:01
   ----------------------------- ---------- 6.0/8.2 MB 2.3 MB/s eta 0:00:01
   ------------------------------ --------- 6.3/8.2 MB 2.2 MB/s eta 0:00:01
   ------------------------------ --------- 6.3/8.2 MB 2.2 MB/s eta 0:00:01
   ------------------------------- -------- 6.6/8.2 MB 2.0 MB/s eta 0:00:01
   ------------------------------- -------- 6.6/8.2 MB 2.0 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.2 MB 1.8 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.2 MB 1.8 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.2 MB 1.8 MB/s eta 0:00:01
   ---------------------------------- ----- 7.1/8.2 MB 1.6 MB/s eta 0:00:01
   ---------------------------------- ----- 7.1/8.2 MB 1.6 MB/s eta 0:00:01
   ---------------------------------- ----- 7.1/8.2 MB 1.6 MB/s eta 0:00:01
   ----------------------------------- ---- 7.3/8.2 MB 1.4 MB/s eta 0:00:01
   ----------------------------------- ---- 7.3/8.2 MB 1.4 MB/s eta 0:00:01
   ----------------------------------- ---- 7.3/8.2 MB 1.4 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.2 MB 1.3 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.2 MB 1.3 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.2 MB 1.3 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.2 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.2 MB 1.2 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.2 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------  8.1/8.2 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  8.1/8.2 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  8.1/8.2 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 1.1 MB/s  0:00:07
Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.62.1-cp312-cp312-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   -------- ------------------------------- 0.5/2.3 MB 409.6 kB/s eta 0:00:05
   -------- ------------------------------- 0.5/2.3 MB 409.6 kB/s eta 0:00:05
   ------------- -------------------------- 0.8/2.3 MB 453.5 kB/s eta 0:00:04
   ------------- -------------------------- 0.8/2.3 MB 453.5 kB/s eta 0:00:04
   ----------------- ---------------------- 1.0/2.3 MB 479.5 kB/s eta 0:00:03
   ----------------- ---------------------- 1.0/2.3 MB 479.5 kB/s eta 0:00:03
   ---------------------- ----------------- 1.3/2.3 MB 504.6 kB/s eta 0:00:03
   ---------------------- ----------------- 1.3/2.3 MB 504.6 kB/s eta 0:00:03
   ---------------------- ----------------- 1.3/2.3 MB 504.6 kB/s eta 0:00:03
   -------------------------- ------------- 1.6/2.3 MB 521.2 kB/s eta 0:00:02
   -------------------------- ------------- 1.6/2.3 MB 521.2 kB/s eta 0:00:02
   ------------------------------- -------- 1.8/2.3 MB 529.9 kB/s eta 0:00:01
   ------------------------------- -------- 1.8/2.3 MB 529.9 kB/s eta 0:00:01
   ------------------------------- -------- 1.8/2.3 MB 529.9 kB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 501.9 kB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 501.9 kB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 501.9 kB/s eta 0:00:01
   ---------------------------------------- 2.3/2.3 MB 483.4 kB/s  0:00:05
Downloading kiwisolver-1.5.0-cp312-cp312-win_amd64.whl (73 kB)
Downloading pillow-12.2.0-cp312-cp312-win_amd64.whl (7.1 MB)
   ---------------------------------------- 0.0/7.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/7.1 MB 365.1 kB/s eta 0:00:18
   -- ------------------------------------- 0.5/7.1 MB 365.1 kB/s eta 0:00:18
   -- ------------------------------------- 0.5/7.1 MB 365.1 kB/s eta 0:00:18
   ---- ----------------------------------- 0.8/7.1 MB 385.8 kB/s eta 0:00:17
   ---- ----------------------------------- 0.8/7.1 MB 385.8 kB/s eta 0:00:17
   ---- ----------------------------------- 0.8/7.1 MB 385.8 kB/s eta 0:00:17
   ---- ----------------------------------- 0.8/7.1 MB 385.8 kB/s eta 0:00:17
   ----- ---------------------------------- 1.0/7.1 MB 370.1 kB/s eta 0:00:17
   ----- ---------------------------------- 1.0/7.1 MB 370.1 kB/s eta 0:00:17
   ----- ---------------------------------- 1.0/7.1 MB 370.1 kB/s eta 0:00:17
   ----- ---------------------------------- 1.0/7.1 MB 370.1 kB/s eta 0:00:17
   ----- ---------------------------------- 1.0/7.1 MB 370.1 kB/s eta 0:00:17
   ------- -------------------------------- 1.3/7.1 MB 316.6 kB/s eta 0:00:19
   ------- -------------------------------- 1.3/7.1 MB 316.6 kB/s eta 0:00:19
   ------- -------------------------------- 1.3/7.1 MB 316.6 kB/s eta 0:00:19
   ------- -------------------------------- 1.3/7.1 MB 316.6 kB/s eta 0:00:19
   -------- ------------------------------- 1.6/7.1 MB 316.6 kB/s eta 0:00:18
   -------- ------------------------------- 1.6/7.1 MB 316.6 kB/s eta 0:00:18
   -------- ------------------------------- 1.6/7.1 MB 316.6 kB/s eta 0:00:18
   -------- ------------------------------- 1.6/7.1 MB 316.6 kB/s eta 0:00:18
   -------- ------------------------------- 1.6/7.1 MB 316.6 kB/s eta 0:00:18
   -------- ------------------------------- 1.6/7.1 MB 316.6 kB/s eta 0:00:18
   -------- ------------------------------- 1.6/7.1 MB 316.6 kB/s eta 0:00:18
   ---------- ----------------------------- 1.8/7.1 MB 278.9 kB/s eta 0:00:19
   ---------- ----------------------------- 1.8/7.1 MB 278.9 kB/s eta 0:00:19
   ---------- ----------------------------- 1.8/7.1 MB 278.9 kB/s eta 0:00:19
   ---------- ----------------------------- 1.8/7.1 MB 278.9 kB/s eta 0:00:19
   ---------- ----------------------------- 1.8/7.1 MB 278.9 kB/s eta 0:00:19
   ---------- ----------------------------- 1.8/7.1 MB 278.9 kB/s eta 0:00:19
   ---------- ----------------------------- 1.8/7.1 MB 278.9 kB/s eta 0:00:19
   ---------- ----------------------------- 1.8/7.1 MB 278.9 kB/s eta 0:00:19
   ----------- ---------------------------- 2.1/7.1 MB 253.7 kB/s eta 0:00:20
   ----------- ---------------------------- 2.1/7.1 MB 253.7 kB/s eta 0:00:20
   ----------- ---------------------------- 2.1/7.1 MB 253.7 kB/s eta 0:00:20
   ----------- ---------------------------- 2.1/7.1 MB 253.7 kB/s eta 0:00:20
   ----------- ---------------------------- 2.1/7.1 MB 253.7 kB/s eta 0:00:20
   ----------- ---------------------------- 2.1/7.1 MB 253.7 kB/s eta 0:00:20
   ------------- -------------------------- 2.4/7.1 MB 247.7 kB/s eta 0:00:20
   ------------- -------------------------- 2.4/7.1 MB 247.7 kB/s eta 0:00:20
   ------------- -------------------------- 2.4/7.1 MB 247.7 kB/s eta 0:00:20
   ------------- -------------------------- 2.4/7.1 MB 247.7 kB/s eta 0:00:20
   -------------- ------------------------- 2.6/7.1 MB 255.5 kB/s eta 0:00:18
   -------------- ------------------------- 2.6/7.1 MB 255.5 kB/s eta 0:00:18
   -------------- ------------------------- 2.6/7.1 MB 255.5 kB/s eta 0:00:18
   ---------------- ----------------------- 2.9/7.1 MB 265.5 kB/s eta 0:00:16
   ---------------- ----------------------- 2.9/7.1 MB 265.5 kB/s eta 0:00:16
   ---------------- ----------------------- 2.9/7.1 MB 265.5 kB/s eta 0:00:16
   ---------------- ----------------------- 2.9/7.1 MB 265.5 kB/s eta 0:00:16
   ----------------- ---------------------- 3.1/7.1 MB 271.8 kB/s eta 0:00:15
   ----------------- ---------------------- 3.1/7.1 MB 271.8 kB/s eta 0:00:15
   ----------------- ---------------------- 3.1/7.1 MB 271.8 kB/s eta 0:00:15
   ----------------- ---------------------- 3.1/7.1 MB 271.8 kB/s eta 0:00:15
   ----------------- ---------------------- 3.1/7.1 MB 271.8 kB/s eta 0:00:15
   ----------------- ---------------------- 3.1/7.1 MB 271.8 kB/s eta 0:00:15
   ------------------- -------------------- 3.4/7.1 MB 264.9 kB/s eta 0:00:14
   ------------------- -------------------- 3.4/7.1 MB 264.9 kB/s eta 0:00:14
   ------------------- -------------------- 3.4/7.1 MB 264.9 kB/s eta 0:00:14
   ------------------- -------------------- 3.4/7.1 MB 264.9 kB/s eta 0:00:14
   ------------------- -------------------- 3.4/7.1 MB 264.9 kB/s eta 0:00:14
   -------------------- ------------------- 3.7/7.1 MB 263.1 kB/s eta 0:00:13
   -------------------- ------------------- 3.7/7.1 MB 263.1 kB/s eta 0:00:13
   -------------------- ------------------- 3.7/7.1 MB 263.1 kB/s eta 0:00:13
   -------------------- ------------------- 3.7/7.1 MB 263.1 kB/s eta 0:00:13
   ---------------------- ----------------- 3.9/7.1 MB 267.5 kB/s eta 0:00:12
   ---------------------- ----------------- 3.9/7.1 MB 267.5 kB/s eta 0:00:12
   ---------------------- ----------------- 3.9/7.1 MB 267.5 kB/s eta 0:00:12
   ----------------------- ---------------- 4.2/7.1 MB 273.5 kB/s eta 0:00:11
   ----------------------- ---------------- 4.2/7.1 MB 273.5 kB/s eta 0:00:11
   ----------------------- ---------------- 4.2/7.1 MB 273.5 kB/s eta 0:00:11
   ----------------------- ---------------- 4.2/7.1 MB 273.5 kB/s eta 0:00:11
   ----------------------- ---------------- 4.2/7.1 MB 273.5 kB/s eta 0:00:11
   ------------------------- -------------- 4.5/7.1 MB 270.6 kB/s eta 0:00:10
   ------------------------- -------------- 4.5/7.1 MB 270.6 kB/s eta 0:00:10
   ------------------------- -------------- 4.5/7.1 MB 270.6 kB/s eta 0:00:10
   ------------------------- -------------- 4.5/7.1 MB 270.6 kB/s eta 0:00:10
   ------------------------- -------------- 4.5/7.1 MB 270.6 kB/s eta 0:00:10
   -------------------------- ------------- 4.7/7.1 MB 270.1 kB/s eta 0:00:09
   -------------------------- ------------- 4.7/7.1 MB 270.1 kB/s eta 0:00:09
   -------------------------- ------------- 4.7/7.1 MB 270.1 kB/s eta 0:00:09
   -------------------------- ------------- 4.7/7.1 MB 270.1 kB/s eta 0:00:09
   ---------------------------- ----------- 5.0/7.1 MB 271.3 kB/s eta 0:00:08
   ---------------------------- ----------- 5.0/7.1 MB 271.3 kB/s eta 0:00:08
   ---------------------------- ----------- 5.0/7.1 MB 271.3 kB/s eta 0:00:08
   ---------------------------- ----------- 5.0/7.1 MB 271.3 kB/s eta 0:00:08
   ---------------------------- ----------- 5.0/7.1 MB 271.3 kB/s eta 0:00:08
   ----------------------------- ---------- 5.2/7.1 MB 271.1 kB/s eta 0:00:07
   ----------------------------- ---------- 5.2/7.1 MB 271.1 kB/s eta 0:00:07
   ----------------------------- ---------- 5.2/7.1 MB 271.1 kB/s eta 0:00:07
   ------------------------------- -------- 5.5/7.1 MB 273.9 kB/s eta 0:00:06
   ------------------------------- -------- 5.5/7.1 MB 273.9 kB/s eta 0:00:06
   ------------------------------- -------- 5.5/7.1 MB 273.9 kB/s eta 0:00:06
   -------------------------------- ------- 5.8/7.1 MB 278.3 kB/s eta 0:00:05
   -------------------------------- ------- 5.8/7.1 MB 278.3 kB/s eta 0:00:05
   -------------------------------- ------- 5.8/7.1 MB 278.3 kB/s eta 0:00:05
   ---------------------------------- ----- 6.0/7.1 MB 284.1 kB/s eta 0:00:04
   ---------------------------------- ----- 6.0/7.1 MB 284.1 kB/s eta 0:00:04
   ----------------------------------- ---- 6.3/7.1 MB 290.4 kB/s eta 0:00:03
   ----------------------------------- ---- 6.3/7.1 MB 290.4 kB/s eta 0:00:03
   ------------------------------------- -- 6.6/7.1 MB 296.5 kB/s eta 0:00:02
   ------------------------------------- -- 6.6/7.1 MB 296.5 kB/s eta 0:00:02
   -------------------------------------- - 6.8/7.1 MB 302.4 kB/s eta 0:00:01
   -------------------------------------- - 6.8/7.1 MB 302.4 kB/s eta 0:00:01
   -------------------------------------- - 6.8/7.1 MB 302.4 kB/s eta 0:00:01
   -------------------------------------- - 6.8/7.1 MB 302.4 kB/s eta 0:00:01
   -------------------------------------- - 6.8/7.1 MB 302.4 kB/s eta 0:00:01
   ---------------------------------------- 7.1/7.1 MB 300.9 kB/s  0:00:23
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib

   ---------------------------------------- 0/7 [pyparsing]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----------- ---------------------------- 2/7 [kiwisolver]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ---------------------- ----------------- 4/7 [cycler]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------------- 7/7 [matplotlib]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.62.1 kiwisolver-1.5.0 matplotlib-3.10.9 pillow-12.2.0 pyparsing-3.3.2
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np

In [3]:
# reading csv
df = pd.read_csv("../Data/Raw Data/Product_Reviews.csv",index_col=0)
df.head(10)

,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
Id,,,,,,,,,
1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...
6,B006K2ZZ7K,ADT0SRK1MGOEU,Twoapennything,0,0,4,1342051200,Nice Taffy,I got a wild hair for taffy and ordered this f...
7,B006K2ZZ7K,A1SP2KVKFXXRU1,David C. Sullivan,0,0,5,1340150400,Great! Just as good as the expensive brands!,This saltwater taffy had great flavors and was...
8,B006K2ZZ7K,A3JRGQVEQN31IQ,Pamela G. Williams,0,0,5,1336003200,"Wonderful, tasty taffy",This taffy is so good. It is very soft and ch...
9,B000E7L2R4,A1MZYO9TZK0BBI,R. James,1,1,5,1322006400,Yay Barley,Right now I'm mostly just sprouting this so my...
10,B00171APVA,A21BT40VZCCYT4,Carol A. Reed,0,0,5,1351209600,Healthy Dog Food,This is a very healthy dog food. Good for thei...

In [6]:
df.isnull().sum()

ProductId                  0
UserId                     0
ProfileName               26
HelpfulnessNumerator       0
HelpfulnessDenominator     0
Score                      0
Time                       0
Summary                   27
Text                       0
dtype: int64

In [8]:
df = df.drop(columns=['Text','Summary','ProfileName'])

In [9]:
df.head()

,ProductId,UserId,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time
Id,,,,,,
1,B001E4KFG0,A3SGXH7AUHU8GW,1,1,5,1303862400
2,B00813GRG4,A1D87F6ZCVE5NK,0,0,1,1346976000
3,B000LQOCH0,ABXLMWJIXXAIN,1,1,4,1219017600
4,B000UA0QIQ,A395BORC6FGVXV,3,3,2,1307923200
5,B006K2ZZ7K,A1UQRSCLF8GW1T,0,0,5,1350777600

In [10]:
df['Time'] = pd.to_datetime(df['Time'], unit='s')

In [11]:
df.head()

,ProductId,UserId,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time
Id,,,,,,
1,B001E4KFG0,A3SGXH7AUHU8GW,1,1,5,2011-04-27
2,B00813GRG4,A1D87F6ZCVE5NK,0,0,1,2012-09-07
3,B000LQOCH0,ABXLMWJIXXAIN,1,1,4,2008-08-18
4,B000UA0QIQ,A395BORC6FGVXV,3,3,2,2011-06-13
5,B006K2ZZ7K,A1UQRSCLF8GW1T,0,0,5,2012-10-21

In [12]:
df.reset_index(drop=True, inplace=True)

In [13]:
df.describe()

,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time
count,568454.000000,568454.00000,568454.000000,568454
mean,1.743817,2.22881,4.183199,2011-01-28 23:16:44.902419712
min,0.000000,0.00000,1.000000,1999-10-08 00:00:00
25%,0.000000,0.00000,4.000000,2010-04-15 00:00:00
50%,0.000000,1.00000,5.000000,2011-07-20 00:00:00
75%,2.000000,2.00000,5.000000,2012-03-26 00:00:00
max,866.000000,923.00000,5.000000,2012-10-26 00:00:00
std,7.636513,8.28974,1.310436,NaN

In [19]:
df.shape

(568454, 6)

In [20]:
df.isnull().sum()

ProductId                 0
UserId                    0
HelpfulnessNumerator      0
HelpfulnessDenominator    0
Score                     0
Time                      0
dtype: int64

In [24]:
# increase the data size

newdf = pd.concat(
    [
        df.assign(UserId=df["UserId"] + "_copy0"),
        df.assign(UserId=df["UserId"] + "_copy1"),
        df.assign(UserId=df["UserId"] + "_copy2")
    ],
    ignore_index=True
)

In [25]:
newdf.head(100)

,ProductId,UserId,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time
0,B001E4KFG0,A3SGXH7AUHU8GW_copy0,1,1,5,2011-04-27
1,B00813GRG4,A1D87F6ZCVE5NK_copy0,0,0,1,2012-09-07
2,B000LQOCH0,ABXLMWJIXXAIN_copy0,1,1,4,2008-08-18
3,B000UA0QIQ,A395BORC6FGVXV_copy0,3,3,2,2011-06-13
4,B006K2ZZ7K,A1UQRSCLF8GW1T_copy0,0,0,5,2012-10-21
...,...,...,...,...,...,...
95,B0019CW0HE,A1BFNM27629VAV_copy0,0,0,5,2011-11-01
96,B0019CW0HE,A18AAABCIJKC5Q_copy0,0,0,5,2011-04-26
97,B0019CW0HE,A3UII2114114PI_copy0,0,0,5,2011-02-10
98,B0019CW0HE,ABZ9F0D94YK45_copy0,0,0,5,2011-01-18
99,B0019CW0HE,A2P6ACFZ8FTNVV_copy0,0,1,1,2012-03-08

In [26]:
newdf.shape

(1705362, 6)

In [27]:
newdf.to_csv(
    "../Data/Processed Data/processed_data.csv",
    index=False,
    encoding="utf-8"
)

In [28]:
# Checking where the processed_data.csv is created and is opening or not 
df2 = pd.read_csv("../Data/Processed Data/processed_data.csv", index_col=0)
df2.head()

,UserId,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time
ProductId,,,,,
B001E4KFG0,A3SGXH7AUHU8GW_copy0,1,1,5,2011-04-27
B00813GRG4,A1D87F6ZCVE5NK_copy0,0,0,1,2012-09-07
B000LQOCH0,ABXLMWJIXXAIN_copy0,1,1,4,2008-08-18
B000UA0QIQ,A395BORC6FGVXV_copy0,3,3,2,2011-06-13
B006K2ZZ7K,A1UQRSCLF8GW1T_copy0,0,0,5,2012-10-21